name: soundcloud-desktop

services:
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_PATH: /app/data/soundcloud-desktop.sqlite
      SOUNDCLOUD_CLIENT_ID: ${SOUNDCLOUD_CLIENT_ID}
      SOUNDCLOUD_CLIENT_SECRET: ${SOUNDCLOUD_CLIENT_SECRET}
      SOUNDCLOUD_REDIRECT_URI: ${SOUNDCLOUD_REDIRECT_URI:-http://localhost:3000/auth/callback}
      SOUNDCLOUD_ACCESS_TOKEN: ${SOUNDCLOUD_ACCESS_TOKEN:-}
    volumes:
      - ./data:/app/data

  app-dev:
    restart: always
    build:
      context: .
      target: deps
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_PATH: /app/data/soundcloud-desktop.sqlite
      SOUNDCLOUD_CLIENT_ID: ${SOUNDCLOUD_CLIENT_ID}
      SOUNDCLOUD_CLIENT_SECRET: ${SOUNDCLOUD_CLIENT_SECRET}
      SOUNDCLOUD_REDIRECT_URI: ${SOUNDCLOUD_REDIRECT_URI:-http://localhost:3000/auth/callback}
      SOUNDCLOUD_ACCESS_TOKEN: ${SOUNDCLOUD_ACCESS_TOKEN:-}
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.build.json:/app/tsconfig.build.json
      - ./nest-cli.json:/app/nest-cli.json
    command: pnpm start:dev
